1:
	gcc -Wall -g -o 1 ./1.c -lpthread
2:
	g++ -Wall -g -o 2 ./2.cpp -lpthread 
3:
	g++ -Wall -g -o 3 ./3.cpp -lpthread
assignment:
	g++ -Wall -g -o a ./assignment.cpp -lpthread
1run:
	./1
2run:
	./2
3run:
	./3
run:
	./a
clean:
	rm -rf 1 2 3 a


